// Generated by scripts/flutter-app-version.sh — do not edit manually.

const String kAppVersionFull = '0.2.0+1';
const String kAppVersionName = '0.2.0';
const String kAppBuildNumber = '1';
const String kMockReleaseLabel = 'mock-v0.2.0';
const String kMockSeedVersion = '1.6.2';
