#!/usr/bin/env bash
# Read Flutter app version from pubspec.yaml and optional mock release metadata.
# Source from build scripts: source "$(dirname "$0")/flutter-app-version.sh" && read_flutter_app_version "$APP_DIR"

read_flutter_app_version() {
  local app_dir="$1"
  local pubspec="$app_dir/pubspec.yaml"
  local release_json

  if [[ ! -f "$pubspec" ]]; then
    echo "Error: pubspec.yaml not found: $pubspec" >&2
    return 1
  fi

  local full
  full="$(awk '/^version:/{print $2; exit}' "$pubspec")"
  FLUTTER_VERSION_FULL="$full"
  FLUTTER_VERSION_NAME="${full%%+*}"
  FLUTTER_BUILD_NUMBER="${full#*+}"
  if [[ "$FLUTTER_BUILD_NUMBER" == "$FLUTTER_VERSION_NAME" ]]; then
    FLUTTER_BUILD_NUMBER="1"
  fi

  FLUTTER_APK_VERSION_SLUG="v${FLUTTER_VERSION_NAME}-b${FLUTTER_BUILD_NUMBER}"

  MONOREPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  release_json="$MONOREPO_ROOT/shared/mock/mobile-release.json"
  MOCK_RELEASE="mock-beta"
  MOCK_SEED_VERSION="—"
  if [[ -f "$release_json" ]]; then
    MOCK_RELEASE="$(python3 -c "import json; print(json.load(open('$release_json'))['mockRelease'])")"
    MOCK_SEED_VERSION="$(python3 -c "import json; print(json.load(open('$release_json'))['seedVersion'])")"
  fi

  export FLUTTER_VERSION_FULL FLUTTER_VERSION_NAME FLUTTER_BUILD_NUMBER
  export FLUTTER_APK_VERSION_SLUG MOCK_RELEASE MOCK_SEED_VERSION
}

write_app_build_info_dart() {
  local app_dir="$1"
  local dart_lib="$app_dir/lib/core/constants/app_build_info.dart"
  mkdir -p "$(dirname "$dart_lib")"
  cat >"$dart_lib" <<EOF
// Generated by scripts/flutter-app-version.sh — do not edit manually.

const String kAppVersionFull = '$FLUTTER_VERSION_FULL';
const String kAppVersionName = '$FLUTTER_VERSION_NAME';
const String kAppBuildNumber = '$FLUTTER_BUILD_NUMBER';
const String kMockReleaseLabel = '$MOCK_RELEASE';
const String kMockSeedVersion = '$MOCK_SEED_VERSION';
EOF
}

write_dist_build_manifest() {
  local dist_dir="$1"
  local app_id="$2"
  local apk_name="$3"
  mkdir -p "$dist_dir"
  cat >"$dist_dir/BUILD_INFO.txt" <<EOF
app=$app_id
apk=$apk_name
version=$FLUTTER_VERSION_FULL
mock_release=$MOCK_RELEASE
seed=$MOCK_SEED_VERSION
built_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
}
